
frequency: 50


imu0: /imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: false
imu0_remove_gravitational_acceleration: false
odom_frame: odom
base_link_frame: chassis
world_frame: odom
