# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: chassis
  map_type: costmap
  update_frequency: 3.0
  publish_frequency: 0.0
  static_map: false
  rolling_window: true
  transform_tolerance: 0.5
  width: 10000
  height: 10000
  resolution: 0.05
  origin_x: -5000.0
  origin_y: -5000.0
